modLoader="javafml"
license="All rights reserved"
loaderVersion="[35.0,)"
credits="vincentmet"
[[mods]]
modId="customquests"
version="1.16.4-1.0.0"
displayName="Custom Quests"
description='''
Quests!!!
'''