modLoader="javafml"
license="All rights reserved"
loaderVersion="[34.1,)"
credits="vincentmet"
[[mods]]
modId="customquests"
version="1.16.3-1.0.0"
displayName="Custom Quests"
description='''
Quests!!!
'''